In [1]:
import numpy as np
import pandas as pd

In [2]:
#Question 1 : pandas version
pandas_version = pd.__version__
pandas_version

'1.3.4'

In [3]:
# uploading laptops dataset 
laptop = pd.read_csv("C:/Users/Narges/OneDrive/Desktop/zoomcamp/laptops.csv")
laptop.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [4]:
# Q2 : no of laptops dataset records
no_record = laptop.index
len(no_record)

2160

In [5]:
# Q4 no of unique laptop brands
Brands = laptop["Brand"].nunique()
Brands

27

In [6]:
# Q5: Missing values
null = laptop.isnull().sum()
null[null!=0].size

3

In [7]:
# Q6: Maximum final price
max_price_of_dell = laptop.loc[laptop["Brand"] == "Dell", "Final Price"].max()
max_price_of_dell

3936.0

In [8]:
# Q6.1: Median value of Screen
median_screen = laptop["Screen"].median()
median_screen

15.6

In [9]:
# Q6.2: Median value of Screen
screen_value_counts = laptop["Screen"].value_counts()
screen_value_counts

15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.50      19
13.40      19
11.60      16
14.20      14
12.30      13
14.10      11
13.60      11
16.20      10
15.30       8
10.50       7
14.40       6
12.40       6
15.40       5
12.00       4
18.00       3
14.50       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: Screen, dtype: int64

In [10]:
# Q6.3: Median value of Screen
laptop["Screen"].fillna(15.60, inplace=True)

In [11]:
# Q6.4: Median value of Screen
new_median_screen = laptop["Screen"].median()
new_median_screen

15.6

In [12]:
# Q6.5: Median value of Screen/ Has it changed?
if new_median_screen == median_screen:
    print("no, it has not changed")


no, it has not changed


In [21]:
# Q7.1-3
innjoo = laptop.loc[laptop["Brand"] == "Innjoo", ["RAM", "Storage", "Screen"]]
x = innjoo.values
x


array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [22]:
# Q7.4
XTX = x.T @ x
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [23]:
# Q7.5
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [24]:
# Q7.6-7
y = np.array([1100, 1300, 800, 900, 1000, 1100])
w = XTX_inverse @ (x.T) @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [25]:
# Q7.8
w_sum = np.sum(w)
w_sum

91.29988062995496